# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Contributor Helper'
description: 'Help you view contributor.'
author: 'xrkffgg'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'users'
  color: 'red'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  repo:
    description: The repository name.
  block-users:
    description: Block users name.
  update-files:
    description: The update files path.
  update-places:
    description: The update files places. Contains start position and end position.
  avatar-width:
    description: The avatar width show.
  style:
    description: The contributor list style. Option simple base detail.
  show-total:
    description: Whether show tatal number.
  show-number:
    description: The number show.
  user-emoji:
    description: Customize the emoji before user.

outputs:
  contributors:
    description: The contributors list.

runs:
  using: 'node12'
  main: 'dist/index.js'
